### ISSUE TITLE
Tag releases and add GitHub Release Notes

### ISSUE THREAD

**Issue by caniszczyk** [twitter/secureheaders#103]
No tags make sad: https://github.com/twitter/secureheaders/releases

Would be great to add github release notes too!
https://github.com/blog/1547-release-your-software

**Comment by bquorning** [comment]
As for the tags, it’s as easy as `rake release` (since your Rakefile has `require 'bundler/gem_tasks'`)

**Comment by bquorning** [comment]
Sorry, I just noticed that the recent tags *are* there. Just with no `v` in front.
