### ISSUE TITLE
[question] Nginx headers

### ISSUE THREAD

**Issue by frodsan** [twitter/secureheaders#129]
Hi,

I have a question that I've been thinking about for a while. If I set the "X-Frame-Options" and "Strict-Transport-Security" headers in my nginx configuration. Can I skip the filters that protect those headers?

Example:

```
add_header Strict-Transport-Security "max-age=631138519; includeSubdomains";
add_header X-Frame-Options "DENY";
```

Thanks in advance.

**Comment by oreoshake** [comment]
> Can I skip the filters that protect those headers?

Certainly! Setting the headers at a "higher" level is always better. Just be sure ALL environments set this header. I can imagine a case where someone developing locally may not have set those headers in their nginx (or they're using webbrick/unicorn/etc directly) so be sure dev matches prod!

**Comment by oreoshake** [comment]
Also, kudos on that config. The internet thanks you for "includeSubdomains". Now just get on that preload list https://hstspreload.appspot.com/

**Comment by frodsan** [comment]
Thank you so much for the advices. I try to add my site to the preload list, but it doesn't support TLS 1.1/TLS1.2. I contacted Adam and he's going to fix it in the next weeks. :smile:
