### ISSUE TITLE
Rails 4 support

### ISSUE THREAD

**Issue by naiyt** [twitter/secureheaders#130]
It seems like secureheaders has some issues on Rails 4 (tested on Rails 4.1.6). The headers being set in my initializer aren't what's actually being served. From what I've read, Rails 4 sets more default headers now, like X-Frame-Options. My assumption is that secureheaders is setting X-Frame-Options first, but then Rails is overwriting it at a later point.

Is this a known issue? If other people are having this issue (and it's not just something to do with how I have it configured) I could look into it and try to create a PR.

**Comment by oreoshake** [comment]
Yeah I had originally proposed that in twitter/secureheaders/issues/69 but never got around to it. I'd love a pull request if you could :smile_cat:

**Comment by naiyt** [comment]
Sure, I'll take a look and see if I can figure out it!

**Comment by oreoshake** [comment]
I think it's just a call to `config.action_dispatch.default_headers.clear` in an initializer block

**Comment by stve** [comment]
> I think it's just a call to `config.action_dispatch.default_headers.clear` in an initializer block

That would clear out any non-security related headers as well as an unintended side-effect, presumably we'd need to only remove headers that are defined in this gem.

**Comment by oreoshake** [comment]
> we'd need to only remove headers that are defined in this gem

Good call.

**Comment by naiyt** [comment]
Yeah, good point., @stve. I'm working on getting a failing spec written right now.

**Comment by naiyt** [comment]
I added a [Rails 4 fixture](https://github.com/naiyt/secureheaders/compare/rails4) trying to match as closely as possible what you have for the Rails 3 fixtures. Oddly, though, I can't seem to get replicate the issue when running those specs.

To test, I set `config.x_frame_options = 'DENY'` [in the initializer](https://github.com/naiyt/secureheaders/blob/550ca519c458fdf5bc041aab67cde80dc86781e0/fixtures/rails_4_1_8/config/initializers/secure_headers.rb#L3). ActionDispatch defaults it to `SameOrigin`.

So I would expect [that this spec should fail](https://github.com/naiyt/secureheaders/blob/550ca519c458fdf5bc041aab67cde80dc86781e0/fixtures/rails_4_1_8/spec/controllers/other_things_controller_spec.rb) on Rails 4. However, it passes, which means secureheaders is setting that header correctly.

Either some quirk of the test environment, or I'm doing something silly. I'll keep looking into it, but if you guys notice anything obvious I'm missing let me know. :+1:

**Comment by naiyt** [comment]
...er, actually that is failing. I just did something silly yesterday.

**Comment by naiyt** [comment]
This is working for me on Rails 4 now with the #131 merge.
