### ISSUE TITLE
Changing a config option for particular action.

### ISSUE THREAD

**Issue by martinpovolny** [twitter/secureheaders#134]
I'd like to lift CSP for a single action in our application. Particularly I'd like to lift the `connect_src` a bit.

I know I can use e.g. `skip_before_filter :set_csp_header, :only => :launch_novnc_console ` but I would prefer to keep the CSP header in and only allow more sources for this single action.

Is there a way? I don't see it reading the doc.

Thanks in advance for any pointers!

**Comment by oreoshake** [comment]
Well you can build/set the header yourself like this: https://github.com/twitter/secureheaders/blob/master/lib/secure_headers.rb#L88

That's probably the best way to modify CSP for a single action. You can also set per-controller configs `ensure_security_headers(:csp => {...}`

**Comment by Christian-Hansen** [comment]
@martinpovolny if you have an example to share it would be great, I would like to do something similar, i.e. add extra `connect_src ` or `script_src` for particular actions.

**Comment by oreoshake** [comment]
And I'll add that example to the `README` or we can come up with a better way of doing this.
