### ISSUE TITLE
undefined local variable or method `ensure_security_headers` when upgrading to `secure_headers 2.0.0`

### ISSUE THREAD

**Issue by raphaelcm** [twitter/secureheaders#135]
I've been using `secure_headers 1.2.0` in production for some time now. Recently I did a `bundle update` and started getting this error on startup:

```
$ rails server
=> Booting WEBrick
=> Rails 3.2.17 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
Exiting
/Users/raphael/bonusly/special_sauce/app/controllers/application_controller.rb:19:in `<class:ApplicationController>': undefined local variable or method `ensure_security_headers' for ApplicationController:Class (NameError)
	from /Users/raphael/bonusly/special_sauce/app/controllers/application_controller.rb:3:in `<top (required)>'
	from /Users/raphael/.rvm/gems/ruby-2.1.5/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:469:in `load'
	from /Users/raphael/.rvm/gems/ruby-2.1.5/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:469:in `block in load_file'
	from /Users/raphael/.rvm/gems/ruby-2.1.5/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:639:in `new_constants_in'
	from /Users/raphael/.rvm/gems/ruby-2.1.5/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:468:in `load_file'
	from /Users/raphael/.rvm/gems/ruby-2.1.5/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:353:in `require_or_load'
	from /Users/raphael/.rvm/gems/ruby-2.1.5/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:502:in `load_missing_constant'
	from /Users/raphael/.rvm/gems/ruby-2.1.5/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:192:in `block in const_missing'
	from /Users/raphael/.rvm/gems/ruby-2.1.5/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:190:in `each'
	from /Users/raphael/.rvm/gems/ruby-2.1.5/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:190:in `const_missing'
```

If I revert back to `secure headers 1.2.0` everything works fine. Did something change in how it's loaded?  Here's my `Gemfile` entry:

`gem 'secure_headers'`

**Comment by raphaelcm** [comment]
Note, I tried: `gem 'secure_headers', require: 'secure_headers'`. No change.

**Comment by oreoshake** [comment]
It sounds like the [`railtie`](https://github.com/twitter/secureheaders/blob/master/lib/secure_headers/railtie.rb) isn't running. I'm assuming dropping `include ::SecureHeaders` will fix the issue, but I'm not sure why this isn't working.

**Comment by raphaelcm** [comment]
`include ::SecureHeaders` did the trick, but shouldn't be necessary, right?

**Comment by oreoshake** [comment]
Definitely not.

**Comment by oreoshake** [comment]
Mind throwing in some debug statements in the railtie class to see if/when things are executing? I can cut a branch if you'd prefer.

**Comment by oreoshake** [comment]
fixed in 2.0.1

**Comment by oreoshake** [comment]
fixed in 2.0.1

**Comment by codesoda** [comment]
@oreoshake I'm getting this same issue on 2.2.2, perhaps a regression?

**Comment by ACPK** [comment]
@oreoshake  I also got this issue with 2.4.3

**Comment by oreoshake** [comment]
So strange, I have never run into this. If anyone has a reproducible test case I can investigate.

**Comment by spectator** [comment]
I run into similar issue upgrading one of the gems and was able to track it down to this code

https://github.com/trailblazer/trailblazer-rails/blob/v0.2.3/lib/trailblazer/rails/railtie.rb#L28-L30 which leads to https://github.com/trailblazer/trailblazer-rails/blob/v0.2.3/lib/trailblazer/rails/application_controller.rb

I'm not exactly sure in the mechanics of why this happens, but fixing offending gem to use `AS#on_load` helps.
