### ISSUE TITLE
Support to safari extension

### ISSUE THREAD

**Issue by sammyshj** [twitter/secureheaders#136]
Currently, twitter blocks any safari extension. To allow, this, 'safari-extension:/' needs to be added under 'frame-src' for the content-security-policy header.

**Comment by oreoshake** [comment]
Hi Sambuddha, this is just the tool that helps configure content security policy. You'd have to ask twitter to change that - and I don't work there anymore. 

But that's actually a safari bug, the spec clearly states that CSP shouldn't interfere with extensions but that's not a reality today.

**Comment by sammyshj** [comment]
Where can I ask twitter to change their CSP response headers?
