### ISSUE TITLE
nonced_javascript_tag does not support options

### ISSUE THREAD

**Issue by jmera** [twitter/secureheaders#138]
In HTML 4, the type attribute is required.  In HTML 5, the `type` attribute is optional and defaults to `text/javascript`... In the current implementation, this presents a problem.  The following won't work:

```erb
<%= nonced_javascript_tag(type: "text/javascript") do %>
  console.log("nonced!");
<% end %>
```

I would expect the following output:

```html
<script type="text/javascript" nonce="abc123">
  console.log("nonced!");
</script>
```

Am I missing something here?

**Comment by oreoshake** [comment]
Just a [poor implementation](https://github.com/twitter/secureheaders/blob/master/lib/secure_headers/view_helper.rb#L48). It certainly does not pass the options along.

**Comment by jmera** [comment]
@oreoshake I'm sure there is a workaround, though.  Just from skimming through the src, I think the following, or something similar, will work (I haven't had a chance to test it out):

```ruby
<%= javascript_tag(type: "text/javascript", nonce: @content_security_policy_nonce) do %>
  console.log("nonced!");
<% end %>
```

**Comment by oreoshake** [comment]
Oh I'm playing around with a branch that will match the existing `javascript_tag` api. btw, `javascript_tag` seems to ignore the `type` value.

**Comment by jmera** [comment]
@oreoshake silly me.  `type` should be implied in this situation... Nonetheless, it'd be nice to be able to pass other options.  Thanks for your help on this!

**Comment by oreoshake** [comment]
I have https://github.com/twitter/secureheaders/tree/pass-options-to-tag-helpers, which works but is just as thoroughly tested as the ViewHelper: not at all. I don't like that.

**Comment by jackphelps** [comment]
This thread was helpful, thanks everyone. 

I felt that for my purposes this was a little complex; I'm using Rails and found it pretty quick to basically fake Stripe.js's Stripe object when in test. I'm using rails and found it pretty quick to just swap out my Stripe.js script call in the template to a custom helper that looks roughly like this:
```
  def stripe_js_script_code
    if Rails.env.test?
      test_script     = helpers.javascript_include_tag 'stripe_test', "data-turbolinks-track" => true
      fake_token_meta = '<meta name="fake-stripe-token" content="' + fake_stripe_token + '">'
      return fake_token_meta + test_script
    else
      '<script src="https://js.stripe.com/v2/" data-turbolinks-track="false"></script>'
    end
  end
```
My script looks like this:
https://gist.github.com/jackphelps/4b4f98ca8c314cb86bc7

**Comment by oreoshake** [comment]
Fixed in the 3.x branch.
