### ISSUE TITLE
CSP render js partial and best practice query?

### ISSUE THREAD

**Issue by cheeyeo** [twitter/secureheaders#152]
Hi

firstly, thanks for the great gem!

I have a quick query on setting the right CSP config for script_src in a rails application?

I have a remote UJS action which has a corresponding '.js.erb' template which runs some javascript when rendered. However, CSP blocks it from working unless I have 'eval' set inside script_src which is not secure.

Are there any recommendations to resolve this?

thanks

**Comment by oreoshake** [comment]
I'm assuming you're using something like:

```js
$.ajax({
    url: 'somewhere',
    type: 'POST',
    dataType: 'script' 
});
```

>  "script": Evaluates the response as JavaScript and returns it as plain text....

From http://api.jquery.com/jquery.ajax/

I'd suggest not using `js.erb`. While it's entirely possible to use it safely, it's so easy to get it wrong and the consequences are pretty bad. If you can describe your use case, I can try to help you come up with a way to accomplish the same task without the use of js.erb.

**Comment by mpugach** [comment]
Hello @oreoshake

I'm in same situation, here is my [js template](https://github.com/KyivKrishnaAcademy/ved_akadem_students/blob/a6b849d1437e4b412858ba7922abb934e7414f3b/app/views/people/move_to_group.js.erb) and here [is the call](https://github.com/KyivKrishnaAcademy/ved_akadem_students/blob/a6b849d1437e4b412858ba7922abb934e7414f3b/app%2Fassets%2Fjavascripts%2Fcustom.js.coffee#L35-L39).

So a person is shown to admin and he can select an academic group to move the person to. When the person group is changed, I want the js.erb to be rendered, so the admin can see new person's group immediately.

What do you suggest me to do?

**Comment by oreoshake** [comment]
I suggest you make the ajax call return the necessary data (`@academic_group.title`, the link to that object, `@academic_group.id`) and move the javascript into the response handler for that ajax request. Separate the code and data.

**Comment by mpugach** [comment]
thank you, than [other case](https://github.com/KyivKrishnaAcademy/ved_akadem_students/blob/a6b849d1437e4b412858ba7922abb934e7414f3b/app/views/study_applications/_common.js.erb) I will move into React component (since the lib is already in the project). What do you think?

**Comment by oreoshake** [comment]
makes sense to me

**Comment by AaronGaim** [comment]
How can I allow render js partial like in the code below, safely?

test.rb

    class TestsController
       def index
           @students = Student.all
           respond_to do |format|
              format.js { render :action=> "list" }
           end
       end
    end

list.js.rb

    $(".source").html("<%= escape_javascript render @students %>");

Thank you.
