### ISSUE TITLE
Support inline style blocks

### ISSUE THREAD

**Issue by reedloden** [twitter/secureheaders#158]
From README:

```
Hash sources are valid for inline style blocks but are not yet supported by secure_headers.
```

Should add support for them. :)

**Comment by oreoshake** [comment]
It shouldn't be difficult to generalize the use of hashes to apply to style tags as well. Not it.

**Comment by oreoshake** [comment]
Supported in 3.2.0 https://github.com/twitter/secureheaders/releases/tag/v3.2.0
