### ISSUE TITLE
undefined method `enforce_csp?' for nil:NilClass

### ISSUE THREAD

**Issue by nathantechie9** [twitter/secureheaders#171]
I am following the config examples on the main github page. But I am receiving this error no matter if I set enforce to true, false or the proc in the example.

**Comment by nathantechie9** [comment]
It looks like the config csp hash isn't recognized. I get the error no matter what is set inside the csp hash.

config.csp = {
      :default_src => "https: inline eval",
      :report_uri => '/uri-directive'
  }

**Comment by oreoshake** [comment]
`enforce_csp?` is a made up method that must be defined on your current user object, if it exists. The CSP hash is indeed recognized but requires a restart between each change since it is in an initializer.
