### ISSUE TITLE
Can't get nonce to work

### ISSUE THREAD

**Issue by nathantechie9** [twitter/secureheaders#182]
I am trying to copy the docs on nonce. Here is my code.

This is the inline haml js.

%script{ nonce: '<%= @content_security_policy_nonce %>' }
      :plain
        Bugsnag.releaseStage = "#{Rails.env}";
        Bugsnag.user = {
          id: "#{current_user.try(:id)}",
          name: "#{current_user.try(:full_name).to_s.gsub(/\W/, '')}",
          email: "#{current_user.try(:email).to_s.gsub(/\W/, '')}"
        };

This is the main piece in the config initializer.

config.csp = {
    enforce: true,
    default_src: "'self'",
    # report_uri: '/uri-directive', # TODO: setup server to receive attack reports
    img_src:       'self https://stats.g.doubleclick.net http://www.google-analytics.com https://*.gravatar.com https://notify.bugsnag.com',
    frame_src:     'self',
    connect_src:   'self',
    font_src:      'self data:',
    media_src:     'self',
    object_src:    'self',
    style_src:     'self',
    script_src:    "'self' nonce 'unsafe-inline' http://www.google-analytics.com https://www.google-analytics.com https://ssl.google-analytics.com http://*.cloudfront.net http://bugsnag.com"
  }

This is the error

Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src http://localhost:3001 'nonce-ZuWNEj6+zooNy+0WgQPu9oDtmA/Rv2EOuuO1l0Pb+ac=' 'unsafe-inline' http://www.google-analytics.com https://www.google-analytics.com https://ssl.google-analytics.com http://*.cloudfront.net http://bugsnag.com").
	

Bugsnag.releaseStage = "developme...

Ambiguous  in Docs
1. use self or 'self' or " 'self' "
2. What is 'nonce-abc123'
3. Where is @content_security_policy_nonce set?

**Comment by oreoshake** [comment]
> Ambiguous in Docs
> 1. use self or 'self' or " 'self' "

both are supported, for now.

> 2. What is 'nonce-abc123'

abc123 is just a demonstration value.

> 3. Where is @content_security_policy_nonce set?

https://github.com/twitter/secureheaders/blob/7efa486ea123ce5a18c43cfe72f6c6f9bf2d31ad/lib/secure_headers/headers/content_security_policy.rb#L268

I can see the nonce is added to the header, but I'm not sure why that instance variable would not be populated. I suppose using `nonce_javascript_tag` doesn't work either? 

I've never used HAML. Does it behave any differently than erb WRT what is in scope, right? Just confirmed that things work in erb land.

Please shared the generated html if you can, and show that the nonce attribute is not populated. 

Also, are there any other inline scripts? Do you have lastpass installed? Plugins generate this warning regularly.

What browser?

**Comment by nathantechie9** [comment]
K. Let me gather the answers.

**Comment by oreoshake** [comment]
Hmm your config does not align with the error message.

1. It's missing 'self' in the error message
2. The error message has https://www.google-analytics.com https://ssl.google-analytics.com
3. The config has  https://stats.g.doubleclick.net  where the error message doesn't

Remember that since this is an initializer it requires a restart between changes.

**Comment by nathantechie9** [comment]
I'll double check comparing the error with the config.

Firefox
41.0.1

I did just find out the script js tag was missing the instance var. I fixed that. Still working on solving error though. Same error.

**Comment by nathantechie9** [comment]
Start of the inline js

<script nonce='ZQYTAwZlACqYW8kaOVOgXAMgJJtV1I958YsKq/9Uw3E='>
      Bugsnag.releaseStage = "development";
      Bugsnag.user = {

**Comment by nathantechie9** [comment]
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src http://localhost:3001 'nonce-ZQYTAwZlACqYW8kaOVOgXAMgJJtV1I958YsKq/9Uw3E=' 'unsafe-inline' http://www.google-analytics.com https://www.google-analytics.com https://ssl.google-analytics.com http://*.cloudfront.net http://bugsnag.com").

Bugsnag.releaseStage = "developme...

**Comment by nathantechie9** [comment]
It's the script_src piece in the config

**Comment by nathantechie9** [comment]
It almost seems like a browser issue because my co-worker got the same config to work on his browser.

**Comment by nathantechie9** [comment]
I got it to work in chrome, but still not in firefox

I had to change default_src to self, instead of https, so this is really pointing to a browser problem

**Comment by oreoshake** [comment]
Hmm yeah I think this is a firefox bug. The script inside my nonced tag does execute but the warning occurs. If you add a report-uri (even if it 404s) and inspected it in the network tab you can see the `script-sample` of the report contains the javascript that just executed. Strange.

**Comment by oreoshake** [comment]
This is very odd. Is the JS running for you? Maybe the warning is a red herring?

**Comment by nathantechie9** [comment]
Ya, it looks like the js is running. I stepped through it with firebug. Wouldn't the js be ignored/not ran if nonce failed?

**Comment by oreoshake** [comment]
Yep. It should never execute. I had to double check CSP was enforced, sure enough it was. Still scratching my head :confused:

**Comment by nathantechie9** [comment]
How does the gem stop js from executing. I don't see how Ruby could tell the browser to not execute the JS?

**Comment by oreoshake** [comment]
Content security policy tells the browser not to execute javascript. If a nonce is supplied, but the script tag does not have a nonce, the browser knows not to execute it because the content security policy does not allow it.

**Comment by nathantechie9** [comment]
So it really comes down to the browser.

**Comment by oreoshake** [comment]
Well it comes down to how the browser interprets the policy provided by the application code. Writing this off as a browser bug for now.
