### ISSUE TITLE
Chrome jquery setAttribute

### ISSUE THREAD

**Issue by nathantechie9** [twitter/secureheaders#185]
jquery's setAttribute is violating CSP style_src. It looks like a bug between Chrome and jQuery. They have been fixing other related bugs on different jquery methods that update the DOM. How can I turn off or allow anything for style_src. I am really more concerned about script_src working right now (xss protection).

**Comment by nathantechie9** [comment]
This worked around it...

style_src:     "self 'unsafe-inline'",

**Comment by oreoshake** [comment]
Yeah, I only know of a handful of sites that don't use 'unsafe-inline' in their style-src because of things like this.
