### ISSUE TITLE
Error when using x_xss_protection

### ISSUE THREAD

**Issue by dglancy** [twitter/secureheaders#186]
I've a config like:

```::SecureHeaders::Configuration.configure do |config|
 config.x_xss_protection = {value: 1, mode: 'block'}
end```

There is more in the config, but I think these are the relevant aspects. When I browse the site using Safari (or any browser), I am getting the following in the console:

```Error parsing header X-XSS-Protection: 1; mode=block, 1: expected semicolon at character position 14. The default protections will be applied.```

The header looks like this when browsing:

![screen shot 2015-10-22 at 20 31 00](https://cloud.githubusercontent.com/assets/334300/10676518/ba6cbe84-78fe-11e5-8488-88a5e1283437.png)

Any ideas?

**Comment by oreoshake** [comment]
Hmm I'm not able to reproduce this:

```bash
$ cat config/initializers/secure_headers.rb | grep x_xss_protection
  config.x_xss_protection = {value: 1, mode: 'block'}
$ curl -I localhost:3000/asdfs -s | grep X-Xss-Protection
  X-Xss-Protection: 1; mode=block
```

What happens when you set `x_xss_protection` to `false` (telling secure headers to not set the header)? I have a feeling something else may be mangling it.

**Comment by dglancy** [comment]
Thanks @oreoshake, much appreciated. I've just noticed this is only happening in our production env, and not staging or development, so you're right: something else up!

**Comment by oreoshake** [comment]
I've seen load balancers and other front end proxies auto-inject / munge headers before. That's the likely culprit.

**Comment by pavanvamsi3** [comment]
What is the exact reason @dglancy? I'm facing that too. But, only in chrome.

**Comment by mgreensmith** [comment]
+1 seeing this as well, not sure where the header is being munged.
