### ISSUE TITLE
Performance issue by `supported_directives` method

### ISSUE THREAD

**Issue by igrep** [twitter/secureheaders#187]
# Problem

The change in https://github.com/twitter/secureheaders/pull/179 can cause a performance issue.

I learned that lib/secure_headers/headers/content_security_policy.rb,
`UserAgentParser.parse(@ua)` in `supported_directives` is executed for each request.
[As user_agent_parser's author is planning to remove](https://github.com/ua-parser/uap-ruby/issues/14), `UserAgentParser.parse(@ua)` is problematic.
Because it loads [common regexps yaml file as large as 4.7k lines](https://github.com/ua-parser/uap-core/blob/master/regexes.yaml) on every call.

# Possible solution

[According to user_agent_parser's README's recommendation](https://github.com/ua-parser/uap-ruby/blob/master/Readme.md#example-usage), we should instantiate a user_agent_parser  by `UserAgentParser::Parser.new`, then cache it.
So, which class / object should cache a user_agent_parser?

**Comment by oreoshake** [comment]
In the upcoming 3.x series I've moved it here: https://github.com/twitter/secureheaders/blob/dd1fd6ab751e6026431be9ecb25e8664f70ee714/lib/secure_headers.rb#L26. I'll do the same for the 2.x series. Thanks.

**Comment by oreoshake** [comment]
2.4.3 has been released with this fix. Thanks!

**Comment by igrep** [comment]
I confirmed it works perfectly on our production environment! :tada: 
Thank you very much for fixing! :+1:
