### ISSUE TITLE
coffee script tag

### ISSUE THREAD

**Issue by nathantechie9** [twitter/secureheaders#189]
I've never had to try and modify a coffee script tag. I don't even know if that's possible. How do I add nonce to it?

:coffee{ nonce: "#{@content_security_policy_nonce}" }

I don't want to search the web for hours only to find out I can't do this. It would be nice if the docs had examples.

**Comment by oreoshake** [comment]
Neither have I and this is certainly out of scope for the project. Please consult your necessary documentation.
