### ISSUE TITLE
CSP Breaking Ajax

### ISSUE THREAD

**Issue by nathantechie9** [twitter/secureheaders#190]
Chrome doesn't show an error. The ajax just fails silently. Firefox at least throws CSP violation errors. Is this another browser bug?

I can't find any documentation related to allowing ajax and DOM updates. It looks like a lot of the jquery set methods are not working whether it's updating css or the DOM.

**Comment by oreoshake** [comment]
This isn't exactly a CSP support forum, but if you'd like assistance we're going to need a lot more information.

"fails silently" - I assume this means you're not seeing a violation report. What does the network tab report? 404? 500? It sounds like you're confident the request took place.

What error does firefox throw?

**Comment by nathantechie9** [comment]
I am just wondering if there's extra security header config options to allow ajax. The browser isn't throwing a csp violation error in the console. It just doesn't fire the ajax code that updates the DOM. It's tough to tell where the problem lies (security headers gem config, browser bug, jquery library violation etc...) In my opinion relying on browsers to implement standards is going to be a disaster. We've already have too many browser compatibility issues over the years with html5, jquery etc... now security is being added. good grief.

**Comment by oreoshake** [comment]
> I am just wondering if there's extra security header config options to allow ajax

connect-src is the directive that controls ajax.

Without more information I can't help you with this.

CSP isn't easy, but it's very possible and amazingly powerful.

**Comment by ACPK** [comment]
@oreoshake - Did you find a fix for CSP?
