### ISSUE TITLE
nonced tags do not work

### ISSUE THREAD

**Issue by xssc** [twitter/secureheaders#200]
the following does not work:

`
<%= nonced_javascript_tag do %>
    alert('test');
<% end %>
`

It does not work for style either. It gives the error: **undefined method `merge' for nil:NilClass**

**Comment by xssc** [comment]
https://github.com/xssc/secureheaders/commit/a200392bac045daa478a24a23c43da21a2a0b3fe

**Comment by xssc** [comment]
https://github.com/twitter/secureheaders/pull/201

**Comment by oreoshake** [comment]
Fixed in https://github.com/twitter/secureheaders/pull/201

**Comment by oreoshake** [comment]
Pushed `3.0.0.pre2` gem out.
