### ISSUE TITLE
install failing

### ISSUE THREAD

**Issue by maia** [twitter/secureheaders#207]
Is there any difference in installing secureheaders in comparison to other gems? The documentation does not have any details, and I keep failing:

1. `gem 'secureheaders'` and `bundle install` leads to: `Could not find gem 'secureheaders' in any of the gem sources listed in your Gemfile or available on this machine.`
2. `gem 'secureheaders', github: 'twitter/secureheaders'` leads to: `Could not find gem 'secureheaders' in git://github.com/twitter/secureheaders.git (at master@d6dc261). Source does not contain any versions of 'secureheaders'`
3. `gem 'secureheaders', git: 'https://github.com/twitter/secureheaders.git', branch: :master` causes the same error on `bundle install` as with option 2 (which I assume is not surprising).

Thanks in advance!

**Comment by oreoshake** [comment]
Hello, use `gem install secure_headers`. I'm actually surprised this unfortunate naming history hasn't caused more confusion :smile:

**Comment by maia** [comment]
thanks!
