### ISSUE TITLE
Add support for 'referrer-policy' header

### ISSUE THREAD

**Issue by reedloden** [twitter/secureheaders#218]
https://w3c.github.io/webappsec-referrer-policy/ outlines it.

**Comment by oreoshake** [comment]
I thought the directive was dropped? Looks like it's a separate header: https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-header.

**Comment by reedloden** [comment]
Ah, MDN docs are outdated then. :(

https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#referrer
https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#Specifications

Ok, closing this out then.

**Comment by oreoshake** [comment]
Re-opening, adding the `referrer-policy` header is certainly within scope

**Comment by reedloden** [comment]
Fixed thanks to #249
