### ISSUE TITLE
Chrome and Firefox won't send form data to HTTP URL from HTTPS site

### ISSUE THREAD

**Issue by monfresh** [twitter/secureheaders#221]
Hello,

I've been spending the past couple of days trying to figure out why Chrome and Firefox are not allowing non-secure URLs through, but have come up empty so far. I was hoping perhaps someone here has come across this and knows whether I'm doing something wrong or if this is a bug in Chrome and/or Firefox.

We are working with partners who have a test server configuration where Site A uses HTTPS, but then after a form submission, redirects to Site B, which uses HTTP. Here is our secure headers config:
```ruby
SecureHeaders::Configuration.default do |config|
  config.hsts = "max-age=#{1.day.to_i}; includeSubDomains"
  config.x_frame_options = 'SAMEORIGIN'
  config.x_content_type_options = 'nosniff'
  config.x_xss_protection = '1; mode=block'
  config.x_download_options = 'noopen'
  config.x_permitted_cross_domain_policies = 'none'
  config.csp = {
    default_src: %w('self'),
    report_only: false,
    frame_src: %w('self'), # deprecated in CSP 2.0
    child_src: %w('self'), # CSP 2.0 only; replaces frame_src
    # frame_ancestors: %w('self'), # CSP 2.0 only; overriden by x_frame_options in some browsers
    form_action: %w('self' *.foo.example.com:*), # CSP 2.0 only
    block_all_mixed_content: true, # CSP 2.0 only
    connect_src: %w('self'),
    font_src: %w('self' data:),
    img_src: %w('self' data:),
    media_src: %w('self'),
    object_src: %w('none'),
    script_src: %w('self' *.newrelic.com *.nr-data.net 'unsafe-inline'),
    style_src: %w('self'),
    base_uri: %w('self'),
  }
  config.hpkp = {
    report_only: false,
    max_age: 60.days.to_i,
    include_subdomains: true,
    pins: [
      { sha256: 'abc' },
      { sha256: '123' }
    ]
  }
end
```
We have tried all of the following in our `form-action`, including hardcoding the full URL itself, and none of them worked. 
```
*://*.foo.example.com:*/*
*.foo.example.com:*
http://*.foo.example.com:*
http://*.foo.example.com:*/*
http://*.foo.example.com:8080/*
```

Chrome keeps saying:
```
Refused to send form data to 'http://baz.foo.example.com:8080/bar/baz/' because it violates the following Content Security Policy directive: "form-action 'self' *://*.foo.example.com:*/*".
```
We tried disabling HSTS (setting `max-age=0`) and `block_all_mixed_content`, but it still fails. We thought it might have been the `8080` port number, but it also fails with non-secure URLs that don't include a port number. If we redirect to an HTTPS URL, it works fine.

We know that we shouldn't be using mixed content, but we'd like to understand whether or not it's possible to whitelist a non-secure URL in this scenario.

Any ideas?

**Comment by oreoshake** [comment]
This is because what you're trying to accomplish introduces mixed content, or a "broken lock" scenario. Generally this should be avoided at all costs. secure_headers will strip the scheme from all sources by default to discourage introducing mixed content.

However, you can set the `:preserve_schemes => true` flag. This was introduced in https://github.com/twitter/secureheaders/pull/212 and is (lightly) documented in the README. I strongly suggest moving whatever your foo.example.com refers to to use HTTPS rather than use this flag, but I understand that is just not an option sometimes.

HSTS has nothign to do with this and yes, `block-all-mixed-content` will also prevent the mixed content scenario you are attempting.

**Comment by oreoshake** [comment]
>   # frame_ancestors: %w('self'), # CSP 2.0 only; overriden by x_frame_options in some browsers

Frame ancestors actually overrides x-frame-options but is only supported by Chrome (and Opera) and Firefox, so I can see why you would say that.

**Comment by monfresh** [comment]
Aha! Thanks for the fast response. `preserve_schemes: true` did the trick. We had upgraded to secure_headers 3.0 a while back, and this option wasn't there, so I missed it.

As for the frame ancestors issue, I forget where I read this, but someone was saying that Chrome and/or Firefox don't follow the spec. They should be using frame ancestors when x-frame-options is present, but they don't. Maybe this has been resolved since that was written?

**Comment by monfresh** [comment]
Here is where I read that: https://www.owasp.org/index.php/Clickjacking_Defense_Cheat_Sheet#Limitations

> Section 7.7.1 of the CSP Spec says X-Frame-Options should be ignored if frame-ancestors is specified, but Chrome 40 & Firefox 35 ignore the frame-ancestors directive and follow the X-Frame-Options header instead.

Looks like this was the case with older versions of Firefox and Chrome. I haven't tested the latest versions.

**Comment by oreoshake** [comment]
> Looks like this was the case with older versions of Firefox and Chrome. I haven't tested the latest versions.

TBH neither have I. But those are ancient versions and I would hope the person who wrote that comment has filed bugs :)

**Comment by ellecer** [comment]
On Firefox 44, it still ignores frame-ancestors directive if X-Frame-Options is present.

**Comment by oreoshake** [comment]
> On Firefox 44, it still ignores frame-ancestors directive if X-Frame-Options is present.

@ellecer that's good to know. Although, I'm not sure we should detect this feature.
