### ISSUE TITLE
Reintroduce script hash integration

### ISSUE THREAD

**Issue by oreoshake** [twitter/secureheaders#230]
The script-src hash integration was removed in the 3.x release simply because it became difficult to manage things and I suspected that it's use was rare. It still exists in the 2.x line, so I didn't completely screw people over, but hash support is something that should be in the 3.x line.

I suspect the code can mostly be cargo culted, so this shouldn't be completely terrible.

**Comment by reedloden** [comment]
Add it for styles as well? ;)

**Comment by oreoshake** [comment]
This shipped (with styles) in 3.2 https://github.com/twitter/secureheaders/releases/tag/v3.2.0
