### ISSUE TITLE
HttpOnly cookies?

### ISSUE THREAD

**Issue by stve** [twitter/secureheaders#236]
I just saw the `secure_cookie` feature that was added in 3.1. Is enforcing `HttpOnly` cookies worth consideration as well? 

If so, perhaps something like the following would make sense:

```ruby
SecureHeaders::Configuration.default do |config|
  config.cookies = {
    secure: true,
    http_only: true
  }
end
```

Unfortunately, the above proposal comes with an API change that you may not want to accommodate.

**Comment by oreoshake** [comment]
Makes sense to me. we can always support both formats for now.

We should also add [same-site cookies support](https://tools.ietf.org/html/draft-west-first-party-cookies-06).

And all 3 settings should accept a whitelist of cookies to exclude from the protection.

**Comment by stve** [comment]
Awesome. This should be pretty easy to implement. So our target is something like this?

```
SecureHeaders::Configuration.default do |config|
  config.cookies = {
    secure: true,
    httponly: true
    samesite: true
    whitelist: [
      'cookie_name',
      'another_cookie'
    ]
  }
end
```

When the cookie is whitelisted, no configuration is enforced and the cookie is left as is.

This is nitpicky, but do you have a preference towards `http_only` or `httponly` (likewise `same_site` or `samesite`)? Personally i'd probably lean towards `httponly` and `samesite`.

**Comment by oreoshake** [comment]
It's probably going to need to be more complex than that.

```ruby
SecureHeaders::Configuration.default do |config|
  config.cookies = {
    secure: { only: ['session_cookie']
    httponly: { 
      except:  [
        'cookie_name',
        'another_cookie'
      ]
    }
    samesite: {
      lax: { only: ['chill_cookie']},
      strict: { only: ['csrf_foken']
    }
  }
end
```

While I don't like this crazy cookie world we live in, flexibility is necessary.

**Comment by stve** [comment]
I opened a pull request to work through it: #238

**Comment by oreoshake** [comment]
:ship: https://github.com/twitter/secureheaders/releases/tag/v3.2.0
