### ISSUE TITLE
Only mark cookies secure for https requests

### ISSUE THREAD

**Issue by oreoshake** [twitter/secureheaders#243]
When using `secure_cookies: true` over plain http, the cookies are marked as secure and are not served on subsequent requests.

Maybe @stve can add this as part of https://github.com/twitter/secureheaders/pull/238 ?

See https://stackoverflow.com/questions/36447768/unable-to-login-to-my-rails-app-after-implenting-secure-headers-gem-in-my-local#new-answer

**Comment by stve** [comment]
That is a really good catch. Feel free to assign this one to me, i'm getting close to finishing my list and can tackle it
