### ISSUE TITLE
Set two csp headers (enforced and report only)

### ISSUE THREAD

**Issue by davidhan527** [twitter/secureheaders#256]
Is there a way using secure headers, to set both an enforced and report only header? A lot of people might want to do this in order to experiment with a different policy configuration and see what violation may occur before actually enforcing it.

**Comment by oreoshake** [comment]
`secure_headers

**Comment by oreoshake** [comment]
`secure_headers` provides classes for generating headers based on configs. However, there isn't a way to do this with just config. 

```ruby
response.headers["Content-Security-Policy"] = ContentSecurityPolicy.new(config, user_agent).value
```

I think this would be a great addition.

**Comment by oreoshake** [comment]
I think adding something like this would work well:

```ruby
SecureHeaders::Configuration.default do |config|
  config.csp = { default_src: 'self' ... }  
  config.csp_report_only = { default_src: 'none' ... }  
end
```

**Comment by oreoshake** [comment]
I was just thinking about this. Specifically, should there be a flag to indicate which policy the override is meant for (that defaults to both)?

```ruby
SecureHeaders::Configuration.default do |config|
   config.csp = {
     default_src: ['none'],
     script_src: %w(example.com anotherexample.com)
   }

   config.csp_report_only = config.csp.merge { 
     script_src: %w(example.com) # more restrictive, fewer hosts
   }
end
```

Somewhere in a controller...

```ruby
append_content_security_policy_directives(:script_src, ['thirdparty.com'], :enforced)
override_content_security_policy_directives(:script_src, ['none'], :report_only)
```

Would result in 

```
Content-Security-Policy: default-src 'none'; script_src example.com anotherexample.com thirdparty.com
Content-Security-Policy-Report-Only: default-src 'none'; script_src 'none'

**Comment by oreoshake** [comment]
fyi there's a PR for this https://github.com/twitter/secureheaders/pull/281
