### ISSUE TITLE
iOS blocks whitelisted script and connect sources

### ISSUE THREAD

**Issue by richardhthomas** [twitter/secureheaders#266]
Hi,
Apologies in advance if this isn't an issue with the gem, but any advice would be appreciated. Using Safari or Chrome on iOS I am getting whitelisted sources blocked. Here's the report from one such occasion...

`

    "csp-report": {
        "document-uri": "http://www.yourpressure.com/blog/why-cant-i-just-check-my-blood-pressure-whenever-i-feel-like-it",
        "violated-directive": "script-src 'self' www.google-analytics.com www.google-cdn.segment.com api.segment.io cdn.segment.com www.google.com platform.twitter.com apis.google.com connect.facebook.net yourpressure.disqus.com a.disquscdn.com 'unsafe-eval' 'unsafe-inline'",
        "blocked-uri": "https://apis.google.com",
        "source-file": "http://www.yourpressure.com/assets/application-98597757cc05f90b2b03482d7286d1670dd82d23516589f1f5ef098ded993ad3.js",
        "line-number": 33
    }
`

As you can see apis.google.com is included in the whitelist, but is being blocked. This also occurs for connect-src directives. None iOS browsers seem to be fine.

Thanks for any pointers.

**Comment by jacobbednarz** [comment]
I came across a similar thing and it's due to going cross protocol in webkit. Can you try being on HTTPS and requesting the same URL?

**Comment by richardhthomas** [comment]
Thanks - that makes sense.
I can see thatt HTTPS would resolve it, or would setting:

`block_all_mixed_content: false`

do the trick as well? Less secure, but a quicker bodge for this morning!
Cheers.

**Comment by jacobbednarz** [comment]
Unfortunately I still think that will report as a CSP violation in webkit. The cross protocol issue is a pain to fix if you're going to take that route whilst not on one protocol.

**Comment by richardhthomas** [comment]
You are absolutely right - just tested allowing mixed content and it still fails.
Many thanks for your help - at least I now understand where the issue is arising.
Sadly, for now the only solution will be to disable CSP until we move to HTTPS.

**Comment by jacobbednarz** [comment]
It's extremely difficult to roll out CSP on a HTTP site primarily due some providers using HTTPS and the origin needing to go cross protocol at times (the webkit bug has been long outstanding and I _think_ it was only just resolved in nightly builds). I started on a similar path and ended up focusing on getting HTTPS everywhere first and it's solved many of the edge cases like the webkit bug.

**Comment by jacobbednarz** [comment]
Another option is to start rolling it out but blanket ignore webkit (it might cover some real underlying issues) but you will get a pretty close feel for where your violations are. Then once you go HTTPS, the webkit stuff should self resolve.

**Comment by richardhthomas** [comment]
Thanks again for your help.
I just found this which gives some detail about the issue:
https://scotthelme.co.uk/safari-doesnt-like-csp/
I have other issues with CSP at the moment which don't make this worth solving now (e.g. I have to allow unsafe-inline JS anyway for CKEditor to work... I think it's being rewritten which will hopefully improve that. I also have to allow unsafe-eval for JS for Google charts to work... etc). But I'll leave it in report only mode and see if the errors dry up in time as bugs are ironed out.

**Comment by oreoshake** [comment]
Bummer, I thought this bug was squashed a while ago. If you set `:preserve_schemes => true` and manually add the http/https where needed, you should be good to go.

**Comment by richardhthomas** [comment]
Thanks oreoshake. I'll try to test this before the week is out.

**Comment by richardhthomas** [comment]
Just to complete this thread, I got the chance to do some more testing today and I can no longer reproduce the original problem. I assume something has been updated somewhere. Thanks for the help.
