### ISSUE TITLE
SameSite=Strict breaks things in recent versions of Chrome

### ISSUE THREAD

**Issue by poblahblahblah** [twitter/secureheaders#268]
As best I can tell, starting in Chrome version 51.0.2704.79 using SameSite=Strict causes a few issues.

I created a bug report in Chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=616795) which got merged into another bug report (https://bugs.chromium.org/p/chromium/issues/detail?id=619603)

The issue we saw is that logins were not persisted between tabs, and that closing a tab would force you to login again. Other users have chimed in with a few more issues related to this.

**Comment by oreoshake** [comment]
Thanks @poblahblahblah. Maybe we should change `true` to mean `lax`. I think the workaround is to use https://github.com/twitter/secureheaders#samesite-cookie-configuration

```ruby
config.cookies = {
  samesite: {
    lax: true
  }
}
```

**Comment by reedloden** [comment]
SameSite seems to break with SAML as well (due to HTTP POST). We had to disable it for session cookies for now.
