### ISSUE TITLE
Split up monolithic documentation

### ISSUE THREAD

**Issue by oreoshake** [twitter/secureheaders#274]
The README is too long and hard to follow. Instead of trimming content, I think it would make sense to split it up into a `docs` directory with discrete files (creating a config, dynamic policies, using different frameworks, cookie management, etc). 

This was originally discussed in https://github.com/twitter/secureheaders/issues/269#issuecomment-228167780 but I'm creating a specific issue for this purpose in case anyone sees this and wants to take on a fairly beginner-friendly task.

The docs could probably use some cleaning up as well as more elaboration on dense topics. 

/cc @connorshea as the originator of the idea.

**Comment by connorshea** [comment]
I can put it together based on the information I've gathered implementing the gem in GitLab :)

**Comment by oreoshake** [comment]
The wiki now exists! If anyone wants to go down that route, everyone should be able to modify it although it appears that only contributors can create pages.

**Comment by jacobbednarz** [comment]
I've started splitting this up locally from the single README but happy to go to the wiki if everyone is happy there. I'm not fussed either way.
