### ISSUE TITLE
secure_headers 4.0

### ISSUE THREAD

**Issue by oreoshake** [twitter/secureheaders#286]
I want to start working on a list of breaking changes for the new version. The idea is to make it harder to do the wrong thing.
- [x] Require `script-src` to be set. Missing `script-src`s inherit from `default-src`. In general `default-src` lists are far too permissive for something like `script-src`.
- [x] Require `object-src` to be set. See ⬆️ 
- [x] Default cookies to secure, httponly, samsite=lax
- [x] Yeah, a search for "deprecated" turns up a few more things we can remove entirely.
- [x] Notice of intent to drop support for <= 2.1 (2.1 EOL'd on April 1, 2017)

**Comment by stve** [comment]
Not really a change per se, but we should remove `SecureHeaders::Configuration#secure_cookies=` as it was deprecated in 3.2.0 and replaced with `SecureHeaders::Configuration#cookies=`

**Comment by oreoshake** [comment]
Yeah, a [search for "deprecated"](https://github.com/twitter/secureheaders/search?utf8=%E2%9C%93&q=deprecated) turns up a few more things we can remove entirely.

**Comment by oreoshake** [comment]
Notice of intent to drop support for <= 2.1 ([2.1 EOL'd on April 1, 2017](https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/))

**Comment by oreoshake** [comment]
The PR to remove < 2.1 support is up [here](https://github.com/twitter/secureheaders/pull/333).

**Comment by oreoshake** [comment]
> - Require `script-src` to be set. Missing `script-src`s inherit from `default-src`. In general `default-src` lists are far too permissive for something like `script-src`.
> - Require `object-src` to be set. See ⬆️ 

These changes are trivial validation changes that should be easy for anyone looking for an easy PR.

> - Default cookies to secure, httponly, samsite=lax

This should be as simple as changing [these three lines](https://github.com/twitter/secureheaders/blob/master/lib/secure_headers/headers/cookie.rb#L19-L22) ⁉️

**Comment by oreoshake** [comment]
Another change I want in 4.0: a better default policy. Currently, the default policy is `default-src https:` which is pretty good but I'd want to at least set `object-src` to none, add `data:` to fonts and images, `unsafe-inline` to `style-src`, and a few others. E.g. https://github.com/hanami/hanami/blob/23b9562f44e1185ab561bab842af0cb8ff217671/spec/support/shared_examples/cli/generate/app.rb#L272

**Comment by oreoshake** [comment]
I've started an upgrade guide here: https://github.com/twitter/secureheaders/blob/master/upgrading-to-4-0.md

**Comment by oreoshake** [comment]
I just pushed [version 4.0.0.alpha01](https://rubygems.org/gems/secure_headers/versions/4.0.0.alpha01). I'll deploy this to github.com and let it bake a while.

**Comment by oreoshake** [comment]
This happened.
