### ISSUE TITLE
Documentation is incorrect for inline CSP helper

### ISSUE THREAD

**Issue by amingilani** [twitter/secureheaders#289]
# Bugs

Checking to make sure i'm on the same page here, `content_security_policy_script_nonce`, and `content_security_policy_style_nonce` gives an error but `content_security_policy_nonce :script` or `content_security_policy_nonce :style` works

**Comment by oreoshake** [comment]
@amingilani looks like you are correct. This is just an oversight and should be added to the api.

However, the preferred way of using nonces is via the `nonced_javascript_tag` and `nonced_style_tag`. Is there a reason these won't work for you (unless view helpers that generate html in general aren't allowed)?

**Comment by amingilani** [comment]
@oreoshake i'm using intercom/intercom-rails which has its own`intercom_script_tag` helper. Nesting it within `nonced_javascript_tag` gives me something like:

```
<script none="xxxxx">
  <script>
    ...
  </script>
</script>
```

Thankfully their helper accepts a nonce value, and plugs it in automatically 😄

**Comment by oreoshake** [comment]
Ah, that makes total sense. I was just curious :smile:.
