### ISSUE TITLE
[Feature Request] Support 'strict-dynamic' by default

### ISSUE THREAD

**Issue by mikispag** [twitter/secureheaders#302]
It would be really cool if you could add support for `'strict-dynamic'` ([W3C](https://w3c.github.io/webappsec-csp/#strict-dynamic-usage)) by default.

Google is offering [Google Patch Rewards](https://csp.withgoogle.com/docs/faq.html#csp-patches) for integrating CSP in popular frameworks and facilitating adoption (as you already did, so please apply!). 

The most recent research on CSP demonstrated that [the whitelist-based approach is intrinsically flawed for XSS mitigation](https://research.google.com/pubs/pub45542.html), and that [a nonce/hash + 'strict-dynamic' policy](https://csp.withgoogle.com/docs/strict-csp.html), similar to the ones already served by important Google products, is in the quasi-totality of cases the only working solution.

There are a lot of misconceptions about CSP, and getting rid of things that are proven not to work is good - the worst thing you can have is a false sense of security.

If you could also add a link to the [CSP Evaluator](https://csp-evaluator.withgoogle.com/) to your README, to let users evaluate the quality of their policy, it would be awesome.

Please do not hesitate to get back to me if you need any additional information or have doubts.

## More resources

- https://csp.withgoogle.com
- https://csp.withgoogle.com/docs/strict-csp.html
- https://csp-evaluator.withgoogle.com
- https://www.google.com/about/appsecurity/patch-rewards/

**Comment by oreoshake** [comment]
@mikispag:
* what would be a safe fallback value for when `strict-dynamic` is not supported? `*` ? Alternatively...
* we make it use a host source list when unsupported, strict-dynamic + nonce/hash when supported?
  * This sounds ideal and something to work towards.
  * I could hook into common script tag helpers, but that won't help people using strings and raw nonces and is typically frowned upon unless there's some global opt in.

**Comment by mikispag** [comment]
All the answers [here](https://csp.withgoogle.com/docs/strict-csp.html#example) 😄 .

**Comment by oreoshake** [comment]
Fixed in 3.5.1
