### ISSUE TITLE
Add support for cookie __HOST prefixes

### ISSUE THREAD

**Issue by oreoshake** [twitter/secureheaders#307]
# Feature Request

https://googlechrome.github.io/samples/cookie-prefixes/

> Cookie Prefixes are a way of "smuggling" information in the name prefix of a cookie to ensure that certain attributes accompany the request to set a cookie. The supported prefixes are:
> 
> __Secure-, which signals to the browser that the Secure attribute is required.
> __Host-, which signals to the browser that both the Path=/ and Secure attributes are required, and at the same time, that the Domain attribute must not be present.
> The __Secure- and __Host- name prefixes do not have any special meaning to browsers that don't support Cookie Prefixes, so you cannot count on those prefixes providing assurances across all browsers.
> 
>

**Comment by stve** [comment]
@oreoshake how would you envision support for this working?

**Comment by oreoshake** [comment]
I'm not sure to be honest. I've forgotten the details of the spec and how it's meant to be used. It seems like secure_headers could handle all the complexities I'm just not sure what that looks like 

/cc @ptoomey3 @mastahyeti

**Comment by stve** [comment]
After looking over the spec, it appears that secure_headers could add prefixes to cookies via configuration. Given our current config options, here's a few takes on it.

1. Mixed into the existing secure config:
```ruby
config.cookies = {
  secure: { except: ['_guest'], prefix: true }, # prefix all but the `_guest` cookies with `__Secure-`
}
```

We'd have to think of the best way to support `__Host-`

2. As a separate `prefix` config:

```ruby
# with booleans (either secure or host could be specified)
config.cookies = {
  prefix: { 
    secure: true,
}

config.cookies = {
  prefix: { 
    host: true,
}

# or with hashes
config.cookies = {
  prefix: { 
    secure: { except: ['_guest'] },
    host: { only: ['_session'] },
}
```

One implementation wrinkle I can envision is a scenario where a prefix is specified in a secure_headers configuration but the cookie is not declared to be secure or has no `path`. 

I'd also imagine an application would need to be equipped to handle a session (or other) cookie that doesn't follow the framework's convention (i.e., Rails expecting `_session`, but it's been overridden to be served as `__Host-_session`). I guess the session cookie could be handled separately, or excluded to sidestep that issue.

**Comment by ptoomey3** [comment]
I'm not all together sure the complexity it worthwhile. The purpose of prefixed headers is to declaratively state the intended policy of a cookie using its name. So, I'm not sure it makes sense for secureheaders to do any magic in terms of auto-prefixing cookie names. If secureheaders wants to do configuration based enforcement of cookie attributes, it could just force things like the `secure` flag and forcing a NULL domain value (making it host only). Plus, even if you did do some auto-name-mangling of cookie names, the cookie's name is still going to be `__HOST-foobar` and would have to be referenced as such by the framework (i.e. you couldn't just access `cookies[:foobar]`), unless lots of mucking around was done to strip the `__Host-` prefix off in middleware or something.

I kind of feel like the goal of prefixed headers is that you can plainly see what the intended policy of the cookie is by simply looking at the cookie's name. And, any attempt to do that automatically may be more confusing that useful. In the end, what does setting this in secureheaders provide someone that simply renaming their cookie does not? I'm not 100% convinced there is no room in here for secureheaders to add something, but my gut reaction was that it felt forced.

**Comment by mastahyeti** [comment]
I agree that having secureheaders add the prefix would be weird. Maybe it could ensure that the app is setting the correct attributes for prefixed cookies though. For example, if it sees a `__Host-foo` cookie without the `secure` flag, it could add it...

**Comment by ptoomey3** [comment]
> For example, if it sees a __Host-foo cookie without the secure flag, it could add it...

I thought the same thing, but I'm also unsure this is wise. It seems like that is more appropriate as some sort of lint test or something. If you are using a feature incorrectly, I don't love the idea of a gem hiding that from you by fixing up your mistake.
