### ISSUE TITLE
Support for Expect-CT header

### ISSUE THREAD

**Issue by renchap** [twitter/secureheaders#321]
This new header informs the browser that it is expected for your certificate to appear in a Certificate Transparency log.

Detailed explanation here: https://scotthelme.co.uk/a-new-security-header-expect-ct/
Browser support: proposed in Chrome, planned for Firefox (https://www.chromestatus.com/feature/5677171733430272)
Specification: https://datatracker.ietf.org/doc/draft-stark-expect-ct/

Sample header: `Expect-CT: enforce; max-age=30; report-uri https://scotthelme.report-uri.io/r/default/ct/enforce`

If `enforce` then the site will not be loaded if the certificate cant be found in a CT log. If absent, then it will only be reported.

**Comment by jacobbednarz** [comment]
I'm going to be playing with this in the near future so if no one picks it up, I'll take a look at adding support for it.
