### ISSUE TITLE
What's the reasoning behind this gem?

### ISSUE THREAD

**Issue by ClaudioCarmeli** [twitter/secureheaders#327]
Hello,
I stumbled upon this gem and wondering, what is the problem that this gem is trying to solve?
Is it to increase Rails security? how? I'd love to understand more and then contribute and write a short wiki maybe as currently there's none.

**Comment by oreoshake** [comment]
Hi @ClaudioCarmeli,

The point of this gem is to provide a way to configure and manage security headers in an application while providing safe defaults, validation of header values, and APIs for dynamically changing values. It also provides configuration options for cookies.

It's an extension of Rails' default_headers mechanism with more bells and whistles.

The combination of safe defaults and high configurability is meant to make adoption of the headers a little bit easier.

**Comment by oreoshake** [comment]
Thanks fro the offer to update the wiki! I'd be happy to help you with any questions you come across along the way.

**Comment by ClaudioCarmeli** [comment]
@oreoshake Thanks a lot! I'll re-read your answer a couple of times more, ask at work and then send a small PR for you to look at.

**Comment by oreoshake** [comment]
@ClaudioCarmeli I'm doing some cleaning and closing this one out. Your wiki additions are always welcome.
