### ISSUE TITLE
Applying manifest_src config to the CSP is ignored

### ISSUE THREAD

**Issue by carlosantoniodasilva** [twitter/secureheaders#338]
Hello, I am trying to add the `manifest_src` option to a CSP configuration, but it doesn't appear to be taken into account.

It appears it's [part of the `DIRECTIVES_3_0`](https://github.com/twitter/secureheaders/blob/v3.6.6/lib/secure_headers/headers/policy_management.rb#L65-L71), but that doesn't seem to be included in any of the [browser specific directives](https://github.com/twitter/secureheaders/blob/v3.6.6/lib/secure_headers/headers/policy_management.rb#L82-L111), thus not being generated in the final CSP header for any browser if I understand it correctly.

[According to MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/manifest-src), `manifest-src` is supported by Chrome and Firefox in both desktop and mobile, and by Opera in desktop (unknown in mobile).

Based on my tests in Chrome (59.0.3071.115), it accepts `manifest-src` in the CSP header just fine (no errors/warnings), but it does complain about the other "directive 3" `reflected-xss` option.

I'm happy to work on a patch, but would like some help/direction on what's the best approach to enable the `manifest_src` option in this case, and if you have any considerations in doing so. Thanks!

### Expected outcome

1. I configure CSP including a `manifest_src` option
2. When I inspect the response headers, the CSP should have included `manifest_src`, but it does not

### Config

This can be reproduced by simple setting the `manifest_src` into a default csp config, resulting in that being part of the configured options but not present in any cached headers for any browser:

```
>> SecureHeaders::Configuration.default { |config| config.csp.manifest_src = ["'self'"] }
=> #<SecureHeaders::Configuration:0x007ffbb554b330 
@hpkp=#<SecureHeaders::NoOpHeaderConfig:0x007ffbb5a6b518>,
@referrer_policy=#<SecureHeaders::NoOpHeaderConfig:0x007ffbb5a6b518>,
@csp=#<SecureHeaders::ContentSecurityPolicyConfig:0x007ffbb554aea8 
  @modified=true, 
  @default_src=["'self'", "https:"], 
  @font_src=["'self'", "https:", "data:"], 
  @img_src=["'self'", "https:", "data:"], 
  @object_src=["'none'"], 
  @script_src=["https:"], 
  @style_src=["'self'", "https:", "'unsafe-inline'"], 
  @manifest_src=["'self'"]>,
@csp_report_only=#<SecureHeaders::NoOpHeaderConfig:0x007ffbb5a6b518>, 
@cached_headers={
  :clear_site_data=>nil, 
  :hsts=>["Strict-Transport-Security", "max-age=631138519"], 
  :x_content_type_options=>["X-Content-Type-Options", "nosniff"], 
  :x_download_options=>["X-Download-Options", "noopen"], 
  :x_frame_options=>["X-Frame-Options", "sameorigin"], 
  :x_permitted_cross_domain_policies=>["X-Permitted-Cross-Domain-Policies", "none"], 
  :x_xss_protection=>["X-XSS-Protection", "1; mode=block"], 
  :csp=>{
    "Chrome"=>["Content-Security-Policy", "default-src 'self' https:; font-src 'self' https: data:; img-src 'self' https: data:; object-src 'none'; script-src https:; style-src 'self' https: 'unsafe-inline'"], 
    "Opera"=>["Content-Security-Policy", "default-src 'self' https:; font-src 'self' https: data:; img-src 'self' https: data:; object-src 'none'; script-src https:; style-src 'self' https: 'unsafe-inline'"], 
    "Firefox"=>["Content-Security-Policy", "default-src 'self' https:; font-src 'self' https: data:; img-src 'self' https: data:; object-src 'none'; script-src https:; style-src 'self' https: 'unsafe-inline'"], 
    "FirefoxTransitional"=>["Content-Security-Policy", "default-src 'self' https:; font-src 'self' https: data:; img-src 'self' https: data:; object-src 'none'; script-src https:; style-src 'self' https: 'unsafe-inline'"], 
    "Safari"=>["Content-Security-Policy", "default-src 'self' https:; font-src 'self' https: data:; img-src 'self' https: data:; object-src 'none'; script-src https:; style-src 'self' https: 'unsafe-inline'"], 
    "Edge"=>["Content-Security-Policy", "default-src 'self' https:; font-src 'self' https: data:; img-src 'self' https: data:; object-src 'none'; script-src https:; style-src 'self' https: 'unsafe-inline'"], 
    "Other"=>["Content-Security-Policy", "default-src 'self' https:; font-src 'self' https: data:; img-src 'self' https: data:; object-src 'none'; script-src https:; style-src 'self' https: 'unsafe-inline'"]}
  }, 
@hpkp_report_host=nil>
```

**Comment by oreoshake** [comment]
:wave: Hi @carlosantoniodasilva, thanks for the report.

As you can tell, this code has rotted a bit. I think the best way forward would be to add `DIRECTIVES_3_0` into the chrome/firefox lists and remove `reflected-xss` since it was dropped entirely.

While we're at it, we could move `block-all-mixed-content` and `upgrade-insecure-requests` to `DIRECTIVES_3_0`.

**Comment by carlosantoniodasilva** [comment]
@oreoshake sounds good, I'll work on a PR with these changes. Thanks!

**Comment by carlosantoniodasilva** [comment]
@oreoshake there you go: #339, thanks!
