### ISSUE TITLE
HSTS headers not set from behind a load balancer doing SSL termination

### ISSUE THREAD

**Issue by n2liquid** [twitter/secureheaders#347]
`Strict-Transport-Security` headers are not sent even though it's asked for in the configuration (`config.hsts = "max-age=#{20.years.to_i}; includeSubdomains"`).

My best guess is that secure_headers ignores this setting when the website is accessed over HTTP. The problem is that I have a load balancer doing SSL termination, so even though the connection to the application server doesn't happen over HTTPS, I think the header *should* be set.

Or, at the very least, I think secure_headers should inspect the `X-Forwarded-Proto` sent by the load balancer, which indicates whether the connection to the LB itself is secure or not, and then determine whether or not to set `Strict-Transport-Security` based on that.

In case those things already happen, could someone help me troubleshoot this issue?

### Relevant software versions

* rack 1.6
* secure_headers 3.6.7

### Expected outcome

1. I configure HSTS (`config.hsts = "max-age=#{20.years.to_i}; includeSubdomains"`).
1. I do SSL termination on a load balancer that properly sets the `X-Forwarded-Proto` request header.
1. When I inspect the response headers, `Strict-Transport-Security` should be present.

### Actual outcome

1. `Strict-Transport-Security` is not present.

### Config

```
  SecureHeaders::Configuration.default do |config|
    config.cookies = {
      secure: true,
      httponly: true,
      samesite: {
        lax: true
      }
    }
    # Add "; preload" and submit the site to hstspreload.org for best protection.
    config.hsts = "max-age=#{20.years.to_i}; includeSubdomains"
    config.x_frame_options = "DENY"
    config.x_content_type_options = "nosniff"
    config.x_xss_protection = "1; mode=block"
    config.x_download_options = "noopen"
    config.x_permitted_cross_domain_policies = "none"
    config.referrer_policy = "no-referrer"
    config.clear_site_data = [
      "cache",
      "cookies",
      "storage",
      "executionContexts"
    ]
    config.csp = {
      # "meta" values. these will shaped the header, but the values are not included in the header.
      # report_only: true,      # default: false [DEPRECATED from 3.5.0: instead, configure csp_report_only]
      preserve_schemes: true, # default: false. Schemes are removed from host sources to save bytes and discourage mixed content.

      # directive values: these values will directly translate into source directives
      default_src: %w('self'),
      base_uri: %w('self'),
      #block_all_mixed_content: true, # see http://www.w3.org/TR/mixed-content/
      child_src: %w('self'), # if child-src isn't supported, the value for frame-src will be set.
      connect_src: %w(),
      font_src: %w('self'),
      form_action: %w('self'),
      frame_ancestors: %w('none'),
      img_src: %w('self' *),
      manifest_src: %w('self'),
      media_src: %w('self'),
      object_src: %w('self'),
      plugin_types: %w(),
      script_src: %w('self' 'unsafe-inline' maps.googleapis.com),
      style_src: %w('self' 'unsafe-inline'),
      #upgrade_insecure_requests: true, # see https://www.w3.org/TR/upgrade-insecure-requests/
    }
  end
```

### Generated headers

```
cache-control:max-age=0, private, must-revalidate
clear-site-data:"cache", "cookies", "storage", "executionContexts"
content-encoding:gzip
content-security-policy:default-src 'self'; base-uri 'self'; child-src 'self'; font-src 'self'; form-action 'self'; frame-ancestors 'none'; img-src *; manifest-src 'self'; media-src 'self'; object-src 'self'; script-src 'self' 'unsafe-inline' maps.googleapis.com; style-src 'self' 'unsafe-inline'
content-type:text/html; charset=utf-8
date:Fri, 28 Jul 2017 03:49:01 GMT
etag:W/"8b61adcbc96d2db706db920d21ff491a"
referrer-policy:no-referrer
server:nginx
set-cookie:_dialog_session=[REDACTED]; domain=[REDACTED]; path=/; HttpOnly; SameSite=Lax
status:200
vary:Accept-Encoding
x-content-type-options:nosniff
x-download-options:noopen
x-frame-options:DENY
x-permitted-cross-domain-policies:none
x-request-id:4ae3cea5-67ab-4062-8aeb-1f2de139ae28
x-runtime:0.506983
x-xss-protection:1; mode=block
```

**Comment by oreoshake** [comment]
Strange. We definitely [check for the value(https://github.com/twitter/secureheaders/blob/master/lib/secure_headers/middleware.rb#L53) of that header] and loadbalancer termination is definitely a common pattern (that I use).

**Comment by oreoshake** [comment]
@n2liquid what version are you using?

**Comment by oreoshake** [comment]
[The code from which this logic was hoisted](https://github.com/tobmatth/rack-ssl-enforcer/blob/6c01471d8dd256590bb1100150e9004d71759904/lib/rack/ssl-enforcer.rb#L124) has changed to fall back to `@request.scheme`.

I suspect the version of `rack` itself is important here.

**Comment by oreoshake** [comment]
Also, adding a middleware that prints out `env` would be helpful in debugging this one.

**Comment by n2liquid** [comment]
Hi, @oreoshake. Yes, I was hesitant to suggest you might not be doing that already, as I think it's a pretty common pattern.

I'm using Rack 1.6 and secure_headers 3.6.7.

Could you suggest a middleware that prints `env`? I'm not sure how to do that since Ruby isn't really my thing; I'm implementing secure_headers on an existing application :)

TIA!

**Comment by oreoshake** [comment]
Thanks for the info, I'll try to reproduce this!

I'm commenting from my phone so the only hacky ways I can think of would be to 

* modify the (unpacked) secureheaders files - not an option if you don't vendor gems
* write a custom middleware and insert it last

It's probably just easier to setup a proxy to inject the request header and throw a debug statement in locally source secureheaders code.

**Comment by n2liquid** [comment]
Good idea, I did `curl -v -H'X-Forwarded-Proto: https' localhost:3000` and got the header back: `Strict-Transport-Security: max-age=631152000; includeSubdomains`.

I just realized it's probably another nginx proxy between the LB and Rails that's probably eating up the header. I'll let you know.

**Comment by oreoshake** [comment]
Ah great, a simple solution worked out better. I was assuming something else in the (app) stack was mucking with things. I'm closing this out but please do re-open if there's further issues.

**Comment by n2liquid** [comment]
Just confirmed the middle proxy was destroying the headers, as with this guy: https://serverfault.com/questions/515957/how-to-have-nginx-forward-the-http-x-forwarded-proto-header

Thanks ;)
