### ISSUE TITLE
Using with turbolinks

### ISSUE THREAD

**Issue by leifcr** [twitter/secureheaders#351]
# Feature Request
When using inline script with nonce parameter, the nonce value is changed for the page request called by turbolinks. This makes the browser not able to run the inline scripts, since they have the wrong nonce value.

## Expected outcome

Expect to have some sort of option to send same nonce value for same session when page is not 'reloaded', and only parts of the page is replaced.

Current behaviour is new nonce value for every request.

Not sure if this is a turbolinks or secureheaders issue.

**Comment by oreoshake** [comment]
I would say this is an issue integrating secureheaders when using turbolinks but neither is really to blame. It seems they are architecturally incompatible without some glue. It'd probably be better to add the glue to secureheaders out of simplicity unless the turbolinks pattern has identified similar issues.

I'm personally not familiar with turbolinks so I'd love it someone else could chime in. We use PJAX, but we also don't use nonces. 

I'm just guessing here, but if you sent the nonce value as a parameter to the next "page request" and set that value as a nonce manually it could work. Tighter integration would definitely be welcome.

**Comment by leifcr** [comment]
@oreoshake I've looked a bit into this, and I'm closing the issue, as the simplest solutions was to yank out inline js and move it to external js files. Since turbolinks does not have an option to pass data back for each request, it will be quite some monkey-patching.

I'll reopen or create a PR if I find a better solution.
