### ISSUE TITLE
Documentation is suggesting a default configuration that is not meant for copy/pasting

### ISSUE THREAD

**Issue by srisa** [twitter/secureheaders#355]
I am using secure_headers gem version 3.6.7 When using Chrome 61, users are not able to log in, there are constantly redirected to the login page(lack of cookies in the request?).

I believe the clear_site_data headers should be present only on the response of logout requests. Currently, it is present in all response headers.

Is there any way to restrict the headers to particular requests?

**Headers in the response.**
<img width="695" alt="screen shot 2017-09-08 at 10 56 23 am" src="https://user-images.githubusercontent.com/10086722/30197329-9f3f6ce4-9484-11e7-83c7-6acb62b71349.png">

**Console error**
<img width="882" alt="screen shot 2017-09-08 at 10 56 01 am" src="https://user-images.githubusercontent.com/10086722/30197364-e29bfffc-9484-11e7-932a-ff02f9e51a54.png">

**Comment by jacobbednarz** [comment]
@srisa are you able to provide the configuration you are using for this? I would imagine this should be in a [per action configuration](https://github.com/twitter/secureheaders/blob/master/docs/per_action_configuration.md) managed by the developer (not the library) since the library doesn't know where your login/logout actions live.

**Comment by oreoshake** [comment]
As usual @jacobbednarz is spot on. I think this means the docs need some updating. Here's the code GitHub uses:

```ruby
class ApplicationController < ActionController::Base
  # Configuratin override to send the Clear-Site-Data header.
  SecureHeaders::Configuration.override(:clear_browser_cache) do |config|
    config.clear_site_data = [
      SecureHeaders::ClearSiteData::CACHE
    ]
  end


  # Clears the browser's cache for browsers supporting the Clear-Site-Data
  # header.
  #
  # Returns nothing.
  def clear_browser_cache
    SecureHeaders.use_secure_headers_override(request, :clear_browser_cache)
  end
end

class SessionsController < ApplicationController
  after_filter  :clear_browser_cache, only: :destroy
end
```

@srisa if this works for you would you be up to providing a patch for the documentation to make this more clear? Using this as a site-wide option will indeed break almost everything.

**Comment by srisa** [comment]
@jacobbednarz I was using the default configuration
@oreoshake Thanks! That worked like a charm. 

I believe default clear_site_data configuration should be blank, and the required headers should be set(by the user) on only specific requests like logout or when the user wishes to clear the data.

If you are ok with this, I'll send a pull request with changes to the documentation.

**Comment by oreoshake** [comment]
I agree. Removing it from the example and adding a specific section with
the above code sample would be best.

**Comment by jacobbednarz** [comment]
@srisa Are you referring to the [configuration](https://github.com/twitter/secureheaders#configuration) section? Reason I ask is that it probably shouldn't be treated as the "default configuration" since it doesn't consider all best practices and in some cases, has potentially dangerous values (I'm looking at you HSTS `max-age` for 20 years and `includeSubdomains`). 

I don't think we could really release a One Size Fits All configuration to solve a bunch of these issues without making the library more specific without more knowledge of the codebases they are running on.

**Comment by oreoshake** [comment]
> has potentially dangerous values (I'm looking at you HSTS `max-age` for 20 years and `includeSubdomains`). 

Go big or go home! But seriously, that `includeSubdomains` would be unfortunate. 

This illustrates a small problem: for a library that provides safe defaults, suggesting a default config is a smell. Perhaps we should emphasize that the provided example is meant to show the configuration options and should not be used as a config.

**Comment by jacobbednarz** [comment]
> Perhaps we should emphasize that the provided example is meant to show the configuration options and should not be used as a config.

I'd be in favour of this in place of the proposed documentation changes further up☝️

**Comment by joecorcoran** [comment]
Just want to chime in and say: yep, we also had difficulties here. Seems we assumed the example was a safe default and not just an extensive example.

It's also mentioned in the [spec](https://w3c.github.io/webappsec-clear-site-data/#fetch-integration) – although not super clearly – that a response with both `Set-Cookie` and `Clear-Site-Data` will even delete the cookie that is presently being set. Nobody's fault here, of course, but probably a good reason to have this header blank by default.

**Comment by oreoshake** [comment]
OK, I've updated the title of this issue to more clearly reflect the problem.

Given secure_headers 4.0 changes the cookie defaults in a drastic way, I think we need to make it clear that the configuration examples are meant to cover all options and highlight the particularly tricky ones. 

This sounds like a bigger rewrite and is one that I should stay out of :smile:

**Comment by srisa** [comment]
I took a stab at this and sent in a PR #356

**Comment by wmakley** [comment]
The example "clear_site_data" setting just took down my app's login when Chrome 61 released the other day. My fault for not understanding what it did, but it highlights a big danger of the documentation as it is currently. I installed secure_headers before the "don't copy paste" warning was added.

**Comment by oreoshake** [comment]
I've removed `clear_site_data` from the README example entirely (along with expect-CT and HPKP). I'd love to hear how we can help improve this further.

**Comment by oreoshake** [comment]
I think the major issues have been addressed. We can iterate from here.
