### ISSUE TITLE
Support worker-src

### ISSUE THREAD

**Issue by renchap** [twitter/secureheaders#357]
`worker-src` should be supported in the CSP header.

It is supported by Chrome 56+.

Documentation on MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src
SPec: https://w3c.github.io/webappsec-csp/#directive-worker-src

**Comment by oreoshake** [comment]
:+1: this should be an easy one for anyone looking to contribute, including first time contributors.

**Comment by arr-dev** [comment]
I could try adding this

**Comment by oreoshake** [comment]
@arr-dev that would be great!
