### ISSUE TITLE
Feature or bug? Chrome 61 removes sessions 

### ISSUE THREAD

**Issue by EsaMakinen** [twitter/secureheaders#359]
After updating to Chrome 61 (latest stable), user sessions are deleted form Rack and Chrome gives console error. No other browsers are affected.

**Console message:**
Clear-Site-Data header on 'http://localhost:': Unrecognized type: {"types":["cache".
(index):1 Clear-Site-Data header on 'http://localhost:4567': Unrecognized type: "executionContexts"]}.

**Secureheaders config:**
    config.clear_site_data = [
      "cache",
      "cookies",
      "storage",
      "executionContexts"
    ]

**Comment by jacobbednarz** [comment]
@EsaMakinen are you able to provide your configuration causing this? #355 and #356 might be of interest to you.

**Comment by EsaMakinen** [comment]
Seems that both tackle the same issue.

My non-functioning config is this, everything works after removing these lines and using it only on logout:

config.clear_site_data = [
"cache",
"cookies",
"storage",
"executionContexts"
]

**Comment by jacobbednarz** [comment]
#355 is the initial bug report where the `clear_site_data` was being applied to all requests (like your report) whereas #356 contains the updated documentation for using per action configuration which correctly applies the `clear_site_data` for particular actions.

**Comment by EsaMakinen** [comment]
Thank you. I'll close this issue as duplicate.
