### ISSUE TITLE
Secure cookies are supposed to default to enabled but when no config is present they are off

### ISSUE THREAD

**Issue by apanzerj** [twitter/secureheaders#365]
# Bugs

Console errors and deprecation warnings are considered bugs that should be addressed with more precise UA sniffing. Bugs caused by incorrect or invalid UA sniffing are also bugs.

### Expected outcome

Describe what you expected to happen 

1. I have no declaration for cookies. Looks like this:

```ruby
SecureHeaders::Configuration.default do |config|
  config.hsts = "max-age=#{20.years.to_i}; includeSubdomains"
#  config.cookies = {
#    secure: true,
#    httponly: true,
#    samesite: {
#      lax: true
#    }
#  }
  config.csp = {
    default_src: %w('self' 'unsafe-inline' 'unsafe-eval' *),
    object_src: %w('none'),
    script_src: %w('self' 'unsafe-inline' unsafe-eval' *)
  }
end
```
2. When I open the console, the cookies should be marked as lax/same-site/secure.

### Actual outcome

1. Cookies are not lax/same-site/secure.

### Config

```ruby
SecureHeaders::Configuration.default do |config|
  config.hsts = "max-age=#{20.years.to_i}; includeSubdomains"
#  config.cookies = {
#    secure: true,
#    httponly: true,
#    samesite: {
#      lax: true
#    }
#  }
  config.csp = {
    default_src: %w('self' 'unsafe-inline' 'unsafe-eval' *),
    object_src: %w('none'),
    script_src: %w('self' 'unsafe-inline' unsafe-eval' *)
  }
end
```

### Generated headers

Provide a sample response containing the headers
```
HTTP/1.1 200 OK
Server: nginx/1.12.1
Date: Tue, 03 Oct 2017 20:29:21 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
ETag: W/"47b215341cb00f3073e31ae651979a2d"
Cache-Control: max-age=0, private, must-revalidate
Set-Cookie: ahoy_visit=***; path=/; expires=Wed, 04 Oct 2017 00:28:18 -0000
Set-Cookie: _tour_app_session=***; path=/; HttpOnly
X-Request-Id: 9b67f834-86d6-464a-a00b-01bb50cd41b5
X-Runtime: 2.900555
Content-Security-Policy: default-src 'unsafe-inline' 'unsafe-eval' *; object-src 'none'; script-src 'unsafe-inline' *
Strict-Transport-Security: max-age=631139040; includeSubdomains
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: sameorigin
X-Permitted-Cross-Domain-Policies: none
X-XSS-Protection: 1; mode=block
```

**Comment by apanzerj** [comment]
If I turn the cookie back on (removing the comment) they work as expected.

**Comment by apanzerj** [comment]
cc @oreoshake

**Comment by oreoshake** [comment]
@apanzerj what version of `secure_headers` are you using?

**Comment by apanzerj** [comment]
4.0.1

**Comment by oreoshake** [comment]
> 4.0.1

Ouch. I'm pretty swamped at the moment 😢 I'm not sure how this would sneak past our tests.

**Comment by apanzerj** [comment]
Hmm. I can look tonight. I have some hunches.

**Comment by apanzerj** [comment]
Putting some notes here in case it helps:

scheme(env) => https
config.cookies => nil

My guess is: if you don't configure cookies at all, then this line:

```
flag_cookies!(headers, override_secure(env, config.cookies)) if config.cookies
```

Doesn't get called. For me, config.cookies is nil by not having any cookies mentioned.

**Comment by apanzerj** [comment]
@oreoshake does this seem correct:

```
      flag_cookies!(headers, override_secure(env, config.cookies)) unless config.cookies == OPT_OUT
```

**Comment by apanzerj** [comment]
Yeah, I'm closer here:

So the SecureHeaders::Cookie class is apparently used on a per cookie basis, but that requires the flag_cookies method to be called, which it isn't. The default that was implemented was only implemented (afaict) inside SecureHeaders::Cookie and not in the configuration class.

**Comment by apanzerj** [comment]
Hmm. Yeah. 

```
irb(main):006:0> SecureHeaders::Configuration.default
=> #<SecureHeaders::Configuration:0x007f86fa0ebf90 @cookies=nil,...
```

**Comment by apanzerj** [comment]
@oreoshake when you have a minute, proposed fix?
