### ISSUE TITLE
Using `override` after using `append_content_security_policy_directives` leads to unexpected behavior

### ISSUE THREAD

**Issue by oreoshake** [twitter/secureheaders#380]
# Bugs

:bug:

### Expected outcome

1. Add CSP changes to the default policy using `append/override_content_security_policy_directives`
1. Use `SecureHeaders.use_secure_headers_override`
1. CSP additions from step 1 are preserved

### Actual outcome

1. CSP additions from step 1 are not preserved

### Example code

```ruby
class ThingController < ApplicationController
  before_action :secure_all_the_things

  SecureHeaders::Configuration.override(:disable_referrer_policy) do |config|
    config.referrer_policy = SecureHeaders::OPT_OUT
  end

  def secure_all_the_things # CSP changes are added and removed here
    append_content_security_policy_directives(script_src: 'foo.com')
    use_secure_headers_override(:disable_referrer_policy)
  end
end
```

@ptoomey3 is working around this issue, but this is surprising behavior. I expected the CSP exceptions to persist even though I'm "overriding" here. Unfortunately, the internals here are a bit messy and the tests are brittle.

Maybe augmenting `named_appends` is a better approach. Also, we could add a `override_referrer_policy` method, similar to `override_x_frame_options`.

**Comment by vuthithanhbinh1220** [comment]
https://github.com/twitter/secureheaders/labels/bug
