### ISSUE TITLE
Add default csp report endpoint

### ISSUE THREAD

**Issue by oreoshake** [twitter/secureheaders#71]
Most people will want to do something pretty custom with their reports. Some will log directly to a public endpoint. Some will implement and endpoint and send it to various sources. [A question on stackoverflow](http://stackoverflow.com/questions/18586572/how-to-view-content-security-policy-violation-reports-in-rails-app#comment27389031_18586572) got me thinking about this.

However, there should be something built in to do some basic aggregation/display with no effort. A few ideas:
- Store in db, create UI for viewing/visualizing, perhaps with search (requires extra config/infra). _Should this be restricted to Rails.env.development?_
- Log to separate log file in human readable format
- Serialize to JSON for use with other visualization tools
- Hook into growl/browser if violations are unexpected? (tangental) 

With a UI, it would be nice to have:
- Policy validator (should this be built into config initialization?)
- Policy adjustment suggestions (restrict/loosen, redundant)
- Indication that inline script, eval script, mixed-content, etc are allowed. With the goal to eliminate all issues.

Supporting this could actually add functionality useful in a prod scenario
- Add a value to the config file that takes a block and yields the JSON hash
- Specify a class name that implements csp_report (essentially no different from a custom endpoint implementation, but pluggable)

I don't think it's wise to try and build something production-ready. And of course, this should involve no code changes other than a configuration tweak.

**Comment by j15e** [comment]
For those still looking for a simple way to gather CSP violation reports, I made a simple rack middleware that reports in my rails logs (thinking of creating a gem but haven't had time yet) : https://gist.github.com/j15e/95898dda12698eb6fd0e

**Comment by oreoshake** [comment]
@j15e very nice! There's also https://report-uri.io/ for the lazy and those less concerned with privacy.

**Comment by j15e** [comment]
Thanks for sharing, I didn't know about `report-uri.io`, nice stuff to begin with.
