### ISSUE TITLE
CSP reports from Chrome not parsed correctly

### ISSUE THREAD

**Issue by EiNSTeiN-** [twitter/secureheaders#79]
**Problem:**
Chrome sets the mime type `application/csp-report` and this prevents the ActionDispatch::ParamsParser middleware from parsing the post body and merging it into the params array. This means that using a forward_endpoint will not work since the [forwarded params array](https://github.com/twitter/secureheaders/blob/master/app/controllers/content_security_policy_controller.rb#L31) will be empty.

**Solution:**

``` ruby
ActionDispatch::ParamsParser::DEFAULT_PARSERS["application/csp-report"] = :json
```

**Comment by JohnColvin** [comment]
Thanks @EiNSTeiN- for the workaround!
